version: "2"

services:
  db:
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - /data/mysql:/var/lib/mysql
    environment:
      MYSQL_USER: test
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
    container_name: "compose-mysql"
    restart: always
    networks:
      - code-network

  redis-6379:
    image: redis
    container_name: "redis-6379"
    ports:
      - "6379:6379"
    networks:
      - code-network
    restart: always

  memcache:
    image: memcached
    ports:
     - "11211:11211"
    container_name: "compose-memcache"
    networks:
      - code-network
    restart: always

  php:
    build:
      context: ./services/php
      dockerfile: Dockerfile
    ports:
     - "9000:9000"
    volumes:
      - /data/htdocs/weiq:/data/ppe
      - /data/htdocs:/data/www/htdocs
    container_name: "compose-php"
    restart: always
    networks:
      - code-network

  web:
    image: nginx:1.11.1
    ports:
      - "80:80"
    depends_on:
      - php
      - memcache
      - redis-6379
    volumes:
      - /data/nginx/vhost:/etc/nginx/conf.d
      - /data/htdocs/weiq:/data/ppe
      - /data/htdocs:/data/www/htdocs
    container_name: "compose-nginx"
    restart: always
    networks:
      - code-network

networks:
  code-network:
    driver: bridge