version: "3.4"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:latest
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=mysql
      - DB_HOST=db:3306
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=gitea*PWD*PWD
    restart: always
    networks:
      - gitea
    volumes:
      - /data/gitea/data:/data
    ports:
      - "3000:3000"
      - "2222:22"
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea*PWD*PWD
      - MYSQL_DATABASE=gitea
    networks:
      - gitea
    ports:
      - "3308:3306"
    volumes:
      - /data/gitea/mysql:/var/lib/mysql